# File just for convenience, for production, the https://github.com/ishlearn/docker -> docker-compose.yml file will be used instead
services:
  web-server:
    build: .
    restart: unless-stopped
    ports:
      - '80:80' # Map local PORT 80 to docker port 80
    environment: # Configure ENV
      PORT: 80
      REDIS_URL: 'redis:6379'
      S3_ENDPOINT: 's3server:8000'
    env_file: .prod.env
    depends_on:
      - redis
      - s3server
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ./storage/mysql:/var/lib/mysql
    env_file: .prod.env
  redis:
    image: redislabs/redismod:preview
    restart: unless-stopped
    ports:
      - '6379:6379'
  s3server:
    image: scality/s3server
    restart: unless-stopped
    ports:
      - '8000:8000'
    env_file: .prod.env
