name: Docker Image CI

on:
  push:
    branches:    
      - 'main'
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ishlearn:latest
        platforms: linux/amd64,linux/arm64
        # cache and multiple platforms only working with buildx: 
        # platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ishlearn:buildcache
        # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ishlearn:buildcache,mode=max
